"""Add project rebuild fields: badge_label, purpose, summary, key_features, outcome

Revision ID: 5235c19dae66
Revises: daa73cb2da8d
Create Date: 2025-12-03 20:10:06.503145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5235c19dae66'
down_revision: Union[str, Sequence[str], None] = 'daa73cb2da8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('badge_label', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('purpose', sa.String(length=200), nullable=True))
    op.add_column('projects', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('key_features', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('outcome', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'outcome')
    op.drop_column('projects', 'key_features')
    op.drop_column('projects', 'summary')
    op.drop_column('projects', 'purpose')
    op.drop_column('projects', 'badge_label')
    # ### end Alembic commands ###
